// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NobleMushroom","status":true,"description":"ノベルゲーム総合プラグイン","parameters":{"表示タイプ初期値":"1","タイトル表示タイプ":"1","コマンド単位ウェイト":"ON","表示速度変数":"1","表示速度初期値":"2","クリック瞬間表示":"ON","自動改行":"ON","相対フォントサイズ":"6","明朝体表示":"ON","ゴシック体表示":"OFF","選択肢接頭辞":"1","画面横サイズ":"0","画面縦サイズ":"0","モバイル画面横サイズ":"480","モバイル画面縦サイズ":"0","モバイルモード":"OFF"}},
{"name":"MakeScreenCapture","status":true,"description":"画面キャプチャ管理プラグイン","parameters":{"PNGキャプチャキー":"F6","JPEGキャプチャキー":"F7","WEBPキャプチャキー":"F9","ファイル名":"image","出力場所":"C:\\OneDrive\\画像\\スクリーンショット","保存形式":"png","連番桁数":"2","タイムスタンプ":"ON","署名":"Triacontane","署名サイズ":"28","署名画像":"","実行間隔":"0","効果音":"Decision1"}}
];
